### ISSUE TITLE
Would you mind to share official implementations of other baseline models in your experiment?

### ISSUE THREAD

**Issue by fxy0715** [cjx96/DisenCDR#3]

**Comment by cjx96** [comment]
Hello~ sorry for the late response, we decided not to share our implementation variants of baselines, as they are beyond our capability to maintain them and answer the related questions. But I can share the codes we referred to as follows:


https://github.com/RUCAIBox/RecBole
https://github.com/rixwew/pytorch-fm
https://github.com/hexiangnan/neural_collaborative_filtering
https://github.com/xiangwang1223/neural_graph_collaborative_filtering
https://github.com/kuandeng/LightGCN
http://home.cse.ust.hk/~ghuac/conet-code_only-hu-cikm18-20181115.zip
https://github.com/lpworld/DDTCDR
https://github.com/WHUIR/PPGN
https://github.com/sunshinelium/Bi-TGCF
